version: '3'

services:
  # db:
  #   image: cassandra:3.11.3
  #   restart: always
  # ports:
  #   - 9042:9042

  
  db:
    image: postgres:9.6-alpine
    restart: always
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    # ports:
    #   - 5432:5432
  
  kong:
    image: kong:0.14.1-alpine
    environment:
      # - KONG_DATABASE=casandra
      # - KONG_CASSANDRA_CONTACT_POINTS=db
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=db
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    depends_on:
      - db
    